force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( StartDate__c   &gt;=    TODAY() , &quot;In Progress&quot;,  IF(  StopDate__c  &gt;=    TODAY(), &quot;Completed&quot;, &quot;Pre-kickOff&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Rol__c/Project_Rol__c.object-meta.xml
<CustomObject>
    <label>Project Rol</label>
    <nameField>
        <label>Project Rol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Rols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Rol__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Rols</relationshipLabel>
    <relationshipName>Project_Rols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Rol__c/fields/Resource_Project_Rol__c.field-meta.xml
<CustomField>
    <fullName>Resource_Project_Rol__c</fullName>
    <label>Resource Project Rol</label>
    <referenceTo>Resource_Project_Rol__c</referenceTo>
    <relationshipLabel>Project Rols</relationshipLabel>
    <relationshipName>Project_Rols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project_Rol__c/Resource_Project_Rol__c.object-meta.xml
<CustomObject>
    <label>Resource Project Rol</label>
    <nameField>
        <label>Resource Project Rol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resource Project Rols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Project_Rol__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resource Project Rols</relationshipLabel>
    <relationshipName>Resource_Project_Rols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Project_Rol__c/fields/Project_Rol__c.field-meta.xml
<CustomField>
    <fullName>Project_Rol__c</fullName>
    <label>Project Rol</label>
    <referenceTo>Project_Rol__c</referenceTo>
    <relationshipLabel>Resource Project Rols</relationshipLabel>
    <relationshipName>Resource_Project_Rols</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Project_Rol__c/fields/StopDate__c.field-meta.xml
<CustomField>
    <fullName>StopDate__c</fullName>
    <label>StopDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Resource_Project_Rol__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resource_Project_Rols</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HandleAssignmentResource.cls
public with sharing class HandleAssignmentResource {
  public static void HandleAssignmentResource(List<Resource_Project_Rol__c> newResources) {
    List<Id> userIds = new List<Id>();
    List<Id> projectRoleIds = new List<Id>();

    for (Resource_Project_Rol__c r : newResources) {
      if (!userIds.contains(r.User__c)) {
        userIds.add(r.User__c);
      }
      if (!projectRoleIds.contains(r.Project_Rol__c)) {
        projectRoleIds.add(r.Project_Rol__c);
      }
    }

    List<Resource_Project_Rol__c> actualResource = [
      SELECT Id, StartDate__c, StopDate__c, User__c
      FROM Resource_Project_Rol__c
      WHERE User__c IN :userIds
      AND Project_Rol__r.Project__r.Status__c != 'Completed'
    ];

    if (actualResource.size() > 0) {
        Map<Id, List<Resource_Project_Rol__c>> ResourceProjectRoleByUserId = new Map<Id, List<Resource_Project_Rol__c>>();

        for (Resource_Project_Rol__c r : actualResource) {
        if (ResourceProjectRoleByUserId.containsKey(r.User__c)) {
            ResourceProjectRoleByUserId.get(r.User__c).add(r);
        } else {
            ResourceProjectRoleByUserId.put(
            r.User__c,
            new List<Resource_Project_Rol__c>{ r }
            );
        }
        }
      //List
        for (Resource_Project_Rol__c nr : newResources) {
            for (Resource_Project_Rol__c r : ResourceProjectRoleByUserId.get(nr.User__c)){
                if (r.StartDate__c < nr.StartDate__c) {
                    if (!(r.StopDate__c < nr.StartDate__c)) {
                        nr.addError('Resource assigned in another project at this date');
                    }
                } else if (r.StartDate__c > nr.StopDate__c) {
                    if (!(r.StopDate__c > nr.StartDate__c)) {
                        nr.addError('Resource assigned in another project at this date');
                    }
                } else {
                    nr.addError('Resource assigned in another project at this date');
                }
            }
        }
    }
    Map<Id, Project_Rol__c> actualProjectRoleById = new Map<Id, Project_Rol__c>([SELECT Id, Project__c, Project__r.StartDate__c, Project__r.StopDate__c 
                                                                                    FROM Project_Rol__c 
                                                                                    WHERE Id IN :projectRoleIds]);


    for (Resource_Project_Rol__c r : newResources) {
      Project_Rol__c actualProjectRole = actualProjectRoleById.get(
        r.Project_Rol__c
      );
      if (
        r.StartDate__c >= actualProjectRole.Project__r.StartDate__c &&
        r.StartDate__c <= actualProjectRole.Project__r.StopDate__c
      ) {
        if (!(
          r.StopDate__c >= actualProjectRole.Project__r.StartDate__c &&
          r.StopDate__c <= actualProjectRole.Project__r.StopDate__c
        )) {
          r.addError('you must assign in project date');
        }
      } else {
        r.addError('you must assign in project date');
      }
    }
  }
}

// for (Resource_Project_Rol__c nr : newResources) {
//     for (Resource_Project_Rol__c r : ResourceProjectRoleByUserId.get(nr.User__c)){
//         if (r.StartDate__c < nr.StartDate__c) {
//             if (r.StopDate__c < nr.StartDate__c) {
//             } else {
//                 nr.addError('Resource assigned in another project at this date');
//             }
//         } else if (r.StartDate__c > nr.StopDate__c) {
//             if (r.StopDate__c > nr.StartDate__c) {
//             //insert
//             } else {
//             nr.addError('Resource assigned in another project at this date');
//             }
//         } else {
//         nr.addError('Resource assigned in another project at this date');
//         }
//     }
// }